language: node_js
node_js:
  - "6"
script:
  - npm test
env:
  global:
  - secure: "Nj6JSL0ghQLJ9xttgtP/vwGpull/weQrE15+nyTKw3iWVZm/nuB3aoP6Lg85SMYm5hezZC8tUyr+PPllPeZc65CS/n2PtyQ8x9ESNafkyAG2vz/B1XlWzm8RcxefrN24vIdo5RxzG3wlB9jVK3EG8GYflNJshe9IxE/924H/onk81UloQUAuenk9GlMrTBb076XX18rJdo/jg2e3pb2hi0aqTyfvKEGcU2CgDSavbUB7XhZmSqjDUm+hRS3PsYt49kn1JRYYwEg2HVhFFWAhGQeYQK5w5VLzaLpU+fRinC6Qdz8cD+SQU5xlCXk2fJ3G+XwJOJHeq9KkQKyCtd21f19XlRaBxtPA1BOQKm/teyi7sA7ZxvNTpKSFS6+oRkjPwdDZytpbNcbWVW8HKqY2e1Mn5wcwRtGdg0Rs1eJ2Dex+nTjNfqHS1/UWME4AIlh7DIuy8KofNaeNZrc1tY2d4rhyLrCgcZlPKeEqKT1FKuervYg8KSDTVnHLIrE+uFAm1mydgu31a3Wn4nLL3yu5MQmMcpJFZJSG/GWK5otvMh3sBn9BIUkb5oZvjLFe4xN5FAVv/oPtNrJDSNzTaAzkPilypH2GP8ZNroG2vxqx0E1XFNHmGqqOgNzvQO38cDaJ++imiQs5uV0uvZvoCKZvXPoFFccJfcTzrMIm9Hn0r3c="
