#      _____                          _
#     / ____|                        | |
#    | (___   ___ _ ____   _____ _ __| | ___  ___ ___
#     \___ \ / _ \ '__\ \ / / _ \ '__| |/ _ \/ __/ __|
#     ____) |  __/ |   \ V /  __/ |  | |  __/\__ \__ \
#    |_____/ \___|_|    \_/ \___|_|  |_|\___||___/___/
#      _____ _
#     / ____| |          | |
#    | (___ | | __ _  ___| | __
#     \___ \| |/ _` |/ __| |/ /
#     ____) | | (_| | (__|   <
#    |_____/|_|\__,_|\___|_|\_\
#
#
#
# This file is the main config file for your bot.
# You can always add more config options for more control.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!


service: slack-sacloud

custom:
  slack_enable_logging: true
  slack_table_name: Teams
  slack_event_path: slack
  slack_install_path: slack
  slack_install_redirect: https://slack.com
  slack_client_scopes: "bot commands incoming-webhook"
  slack_client_id: ${file(local.yml):slack.slack_client_id}
  slack_client_secret: ${file(local.yml):slack.slack_client_secret}
  slack_verification_token: ${file(local.yml):slack.slack_verification_token}

provider:
  name: aws
  runtime: nodejs4.3
  profile: serverless
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"
  environment:
    TABLE_NAME: ${self:custom.slack_table_name}
    CLIENT_ID: ${self:custom.slack_client_id}
    CLIENT_SECRET: ${self:custom.slack_client_secret}
    CLIENT_SCOPES: ${self:custom.slack_client_scopes}
    INSTALL_REDIRECT: ${self:custom.slack_install_redirect}
    VERIFICATION_TOKEN: ${self:custom.slack_verification_token}
    ENABLE_LOGGING: ${self:custom.slack_enable_logging}
    SACLOUD_ACCESS_TOKEN: ${file(local.yml):sacloud.SACLOUD_ACCESS_TOKEN}
    SACLOUD_ACCESS_TOKEN_SECRET: ${file(local.yml):sacloud.SACLOUD_ACCESS_TOKEN_SECRET}

functions:
  slack:
    handler: handler.slack
    events:
      ## Slash Commands, Events, and Interactive Messages
      - http:
          path: ${self:custom.slack_event_path}
          method: post
          integration: lambda
          response:
            template: $input.path('$')

      ## OAuth Routes
      - http:
          path: ${self:custom.slack_install_path}
          method: get
          integration: lambda
          request:
            parameters:
              querystrings:
                code: true
                state: true
          response:
            statusCodes:
              201:
                pattern: ''
              301:
                pattern: http.*
                headers:
                  Location: integration.response.body.errorMessage
                  Cache-Control: "'no-cache, no-store, must-revalidate'"


resources:
  Resources:
    TeamsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.slack_table_name}
